# Generated by Django 5.0.1 on 2024-01-31 19:52

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('title', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=512, null=True)),
                ('cover', models.TextField(null=True)),
                ('pages', models.IntegerField()),
                ('unique_url', models.CharField(default=uuid.UUID('b3f08ea0-82cb-40f6-95b8-dc5118d7a29c'), max_length=32)),
                ('article', models.CharField(default='67220194', max_length=32)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 1, 31, 19, 52, 35, 58557))),
            ],
        ),
        migrations.CreateModel(
            name='BooksBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('book_id', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 1, 31, 19, 52, 35, 59850))),
                ('is_returned', models.BooleanField(default=False)),
                ('returned_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BooksGenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('gener_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BooksPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('page', models.IntegerField()),
                ('page_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BooksStash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FAN', 'FAN'), ('MEL', 'MEL'), ('MUS', 'MUS'), ('DET', 'DET'), ('COM', 'COM'), ('STU', 'STU'), ('LER', 'LER'), ('HOR', 'HOR')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('father_name', models.CharField(max_length=32, null=True)),
                ('is_author', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 1, 31, 19, 52, 35, 58194))),
            ],
        ),
    ]
