# Generated by Django 5.0.1 on 2024-01-31 20:01

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='article',
            field=models.CharField(default='99597947', max_length=32),
        ),
        migrations.AlterField(
            model_name='books',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 20, 1, 21, 80671, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='books',
            name='unique_url',
            field=models.CharField(default=uuid.UUID('19ac1a54-83fe-45b7-be4f-05c06788e99f'), max_length=32),
        ),
        migrations.AlterField(
            model_name='booksbooking',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 20, 1, 21, 83008, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 20, 1, 21, 80078, tzinfo=datetime.timezone.utc)),
        ),
    ]
