# Generated by Django 5.0.1 on 2024-02-01 05:18

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_books_article_alter_books_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='article',
            field=models.CharField(default='7730624', max_length=32),
        ),
        migrations.AlterField(
            model_name='books',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 5, 18, 52, 701789, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='books',
            name='unique_url',
            field=models.CharField(default=uuid.UUID('96cc72ac-e104-4f37-ac73-cef43044eb54'), max_length=32),
        ),
        migrations.AlterField(
            model_name='booksbooking',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 5, 18, 52, 703026, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 5, 18, 52, 701406, tzinfo=datetime.timezone.utc)),
        ),
    ]
