# Generated by Django 5.0.1 on 2024-02-01 05:21

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_books_article_alter_books_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='article',
            field=models.CharField(default='89476535', max_length=32),
        ),
        migrations.AlterField(
            model_name='books',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 5, 21, 44, 608253, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='books',
            name='unique_url',
            field=models.CharField(default=uuid.UUID('30cee286-e56b-4988-b625-d920ba5d4661'), max_length=32),
        ),
        migrations.AlterField(
            model_name='booksbooking',
            name='created_at',
            field=models.DateTimeField(default='2024-02-01 05:21:44.609488'),
        ),
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 5, 21, 44, 607893, tzinfo=datetime.timezone.utc)),
        ),
    ]
