# Generated by Django 5.0.1 on 2024-02-01 05:28

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_books_article_alter_books_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='article',
            field=models.CharField(default='20190798', max_length=32),
        ),
        migrations.AlterField(
            model_name='books',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 5, 28, 48, 464445, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='books',
            name='unique_url',
            field=models.CharField(default=uuid.UUID('1e57e87b-b06b-4347-9779-a19587fbec0a'), max_length=32),
        ),
        migrations.AlterField(
            model_name='booksbooking',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 5, 28, 48, 464077, tzinfo=datetime.timezone.utc)),
        ),
    ]
